In [19]:
### 1. Write a Python Program to Add Two Matrices?
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[6,5,4],[3,2,1]])
print("Matrix before addition")
print(arr)
print(arr1)
print("Matrix after addition")
sum=np.array(arr)+np.array(arr1)
print(sum)




Matrix before addition
[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]
Matrix after addition
[[7 7 7]
 [7 7 7]]


In [20]:
### 2. Write a Python Program to Multiply Two Matrices?
matrix1 = [[6, 7, 3],
         [4, 5, 6],
         [7, 8, 9]]
 
# take a 3x4 matrix
matrix2= [[5, 8, 1, 2],
         [6, 7, 3, 0],
         [4, 5, 9, 1]]
matrixres=0
matrixres=np.dot(matrix1,matrix2) 
print(matrixres)        
 

[[ 84 112  54  15]
 [ 74  97  73  14]
 [119 157 112  23]]


In [16]:
### 3. Write a Python Program to Transpose a Matrix?
import numpy
matrix1 = [[6, 7, 3],
         [4, 5, 6],
         [7, 8, 9]]
transpose=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        transpose[j][i]=matrix1[i][j]  
print("The transpose of matrix1 is: ")  
for res in transpose:    
   print(res)            

The transpose of matrix1 is: 
[6, 4, 7]
[7, 5, 8]
[3, 6, 9]


In [21]:
### 4. Write a Python Program to Sort Words in Alphabetic Order?
character = input("Enter a string: ")
words = character.split()
words.sort()
for word in words:
   print(word)

i
india
love


In [18]:
### 5. Write a Python Program to Remove Punctuation From a String?
test_str = "FSDA, is best : for ! grow rich ;"
print("The original string is : " + test_str)
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for ele in test_str:
	if ele in punc:
		test_str = test_str.replace(ele, "")
print("The string after punctuation filter : " + test_str)


The original string is : FSDA, is best : for ! grow rich ;
The string after punctuation filter : FSDA is best  for  grow rich 
